### ISSUE TITLE
Chyby v logu: Undefined offset

### ISSUE THREAD

**Issue by PeNov** [smartsupp/plugin-prestashop-1.7#1]
Dobrý den,

Verze 2.1.6 generuje mnoho chyb v logu serveru:

Undefined offset: 0 in /home/www/domena.cz/www/domena.cz/modules/smartsupp/smartsupp.php on line 215

Děkuji

Přeji pěkný den

**Comment by krsiakdaniel** [comment]
Dobry den,

diky za informaci, predame na vyvojare.

**Comment by krsiakdaniel** [comment]
fixed
